export const StaticCuisines = [
  { cuisineType: 'African', isActive: false },
  { cuisineType: 'American', isActive: false },
  { cuisineType: 'British', isActive: false },
  { cuisineType: 'Cajun', isActive: false },
  { cuisineType: 'Caribbean', isActive: false },
  { cuisineType: 'Chinese', isActive: false },
  { cuisineType: 'Eastern European', isActive: false },
  { cuisineType: 'European', isActive: false },
  { cuisineType: 'French', isActive: false },
  { cuisineType: 'German', isActive: false },
  { cuisineType: 'Greek', isActive: false },
  { cuisineType: 'Indian', isActive: false },
  { cuisineType: 'Irish', isActive: false },
  { cuisineType: 'Italian', isActive: false },
  { cuisineType: 'Japanese', isActive: false },
  { cuisineType: 'Jewish', isActive: false },
  { cuisineType: 'Korean', isActive: false },
  { cuisineType: 'Latin American', isActive: false },
  { cuisineType: 'Mediterranean', isActive: false },
  { cuisineType: 'Mexican', isActive: false },
  { cuisineType: 'Middle Eastern', isActive: false },
  { cuisineType: 'Nordic', isActive: false },
  { cuisineType: 'Southern', isActive: false },
  { cuisineType: 'Spanish', isActive: false },
  { cuisineType: 'Thai', isActive: false },
  { cuisineType: 'Vietnamese', isActive: false },
];
export const StaticCuisinesExclude = [
  { cuisineType: 'African', isActive: false },
  { cuisineType: 'American', isActive: false },
  { cuisineType: 'British', isActive: false },
  { cuisineType: 'Cajun', isActive: false },
  { cuisineType: 'Caribbean', isActive: false },
  { cuisineType: 'Chinese', isActive: false },
  { cuisineType: 'Eastern European', isActive: false },
  { cuisineType: 'European', isActive: false },
  { cuisineType: 'French', isActive: false },
  { cuisineType: 'German', isActive: false },
  { cuisineType: 'Greek', isActive: false },
  { cuisineType: 'Indian', isActive: false },
  { cuisineType: 'Irish', isActive: false },
  { cuisineType: 'Italian', isActive: false },
  { cuisineType: 'Japanese', isActive: false },
  { cuisineType: 'Jewish', isActive: false },
  { cuisineType: 'Korean', isActive: false },
  { cuisineType: 'Latin American', isActive: false },
  { cuisineType: 'Mediterranean', isActive: false },
  { cuisineType: 'Mexican', isActive: false },
  { cuisineType: 'Middle Eastern', isActive: false },
  { cuisineType: 'Nordic', isActive: false },
  { cuisineType: 'Southern', isActive: false },
  { cuisineType: 'Spanish', isActive: false },
  { cuisineType: 'Thai', isActive: false },
  { cuisineType: 'Vietnamese', isActive: false },
];
export const StaticMealTypes = [
  { cuisineType: 'main course', isActive: false },
  { cuisineType: 'side dish', isActive: false },
  { cuisineType: 'dessert', isActive: false },
  { cuisineType: 'appetizer', isActive: false },
  { cuisineType: 'salad', isActive: false },
  { cuisineType: 'bread', isActive: false },
  { cuisineType: 'breakfast', isActive: false },
  { cuisineType: 'soup', isActive: false },
  { cuisineType: 'beverage', isActive: false },
  { cuisineType: 'sauce', isActive: false },
  { cuisineType: 'marinade', isActive: false },
  { cuisineType: 'fingerfood', isActive: false },
  { cuisineType: 'snack', isActive: false },
  { cuisineType: 'drink', isActive: false },
];

export interface CuisineCategory {
  cuisineType : string;
  isActive: boolean;
}
